auction/urls.py
# auction/urls.py
from django.urls import path
from .views import profile_list, profile_detail, place_bid

app_name = "auction"

urlpatterns = [
    path('profiles/', profile_list, name='profile_list'),
    path('profiles/<int:profile_id>/', profile_detail, name='profile_detail'),
    path('profiles/<int:profile_id>/bid/', place_bid, name='place_bid'),
]

core/account/urls.py
from django.urls import path
from . import views

app_name = "account"


urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

messaging/urls.py

# messaging/urls.py
from django.urls import path
from .views import inbox, send_message, view_conversation

app_name = 'messaging'

urlpatterns = [
    path('inbox/', inbox, name='inbox'),
    path('send_message/<int:receiver_id>/', send_message, name='send_message'),
    path('view_conversation/<int:receiver_id>/', view_conversation, name='view_conversation'),
]

showroom/urls.py
from django.urls import path
from . import views


app_name = 'showroom'

urlpatterns = [
    path('', views.profileListView, name='home_list'),
    path('<int:Profile_id>', views.profiledetailView, name='profiles'),
    path('contact/', views.ContactView, name='contact'),
    path('new_profile', views.newView, name='new_profile'),
    path('search/', views.search_profiles, name='search_profiles'),
    path('Aboutus/', views.about_us_view, name='Aboutus'),
    path('Inventory/', views.Inventory_view, name='Inventory'),
]

urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account", include('account.urls')),
    path("", include('showroom.urls')),
    path("auction/", include('auction.urls')),  # Add this line to include the auction app URLs,
    path('messaging/', include('messaging.urls', namespace='messaging')),

    
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

showroom/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.conf import settings
fs = FileSystemStorage(location=settings.MEDIA_ROOT)

# Create your models here.

class Profile(models.Model):
    name = models.CharField(max_length=50)
    variant = models.CharField(max_length=50)
    engine = models.PositiveIntegerField()
    year = models.PositiveIntegerField()
    mat = [ 
        ('yes','INSURED '),
        ('no','NOT INSURED '),
    ]
    insured = models.CharField(max_length=3 , choices=mat )
    pic = models.ImageField(null = True)
    addpic = models.ImageField(null= True, blank= True)
    price = models.PositiveBigIntegerField(null = True , blank= True)
    Mileage = models.PositiveIntegerField(help_text= "In KMs", null = True, blank = True)
    
    contact  = models.EmailField(null = True)
    bid_start_date = models.DateTimeField()
    bid_end_date = models.DateTimeField()

    def get_winning_bid(self):
        return self.bid_set.filter(is_winner=True).first()


    def save(self, *args, **kwargs):
        print(f"Data Updated for {self.name}")
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

            

showroom/forms.py
from django import forms
from django.core.validators import EmailValidator
from .models import Profile


class ContactForm(forms.Form):
    name=forms.CharField(max_length=100)
    email = forms.CharField(),
    variant = forms.CharField(max_length=50)
    add = forms.CharField(widget=forms.Textarea)

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')

        return cleaned_data


class ProfileForm(forms.ModelForm):
    bid_start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'placeholder': 'YYYY-MM-DD'}))
    bid_end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'placeholder': 'YYYY-MM-DD'}))

    class Meta:
        model = Profile 
        fields = "__all__"

showroom/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from .models import Profile
from .forms import ContactForm , ProfileForm
from django.forms import formset_factory
from django.contrib.auth.decorators import login_required
from django.db.models import Q


def profileListView(request):
    sort_by = request.GET.get('sort')

    if sort_by not in ['name', 'variant', 'year']:
        sort_by = '-bid_end_date'

    # Fetch profiles and apply sorting
    all_profiles = Profile.objects.all().order_by(sort_by)
    paginator = Paginator(all_profiles, 6)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'showroom/home_list.html', {'profiles': page_obj})

@login_required
def profiledetailView(request,Profile_id):
    profil = Profile.objects.get(id=Profile_id)
    return render (request ,'showroom/profiles.html',{'profile': profil})

def ContactView(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)
        
        if form.is_valid():
            print(f"NAME: {form.cleaned_data['name']}")
            print(f"EMAIL: {form.cleaned_data['variant']}")
            print(f"MESSAGE: {form.cleaned_data['year']}")
    
    if request.method == 'GET':
        form = ContactForm()
    
    return render (request, 'showroom/contact.html', {'form':form})


    
# showroom/views.py
from django.shortcuts import render, redirect
from django.forms import formset_factory
from .forms import ProfileForm
from .models import Profile

@login_required(login_url='account:login')
def newView(request):
    profile_formset = formset_factory(ProfileForm, extra=1)

    if request.method == 'POST':
        formset = profile_formset(request.POST, request.FILES)

        if formset.is_valid():
            for form in formset:
                if form.has_changed():
                    profile = form.save(commit=False)
                    profile.bid_start_date = form.cleaned_data['bid_start_date']
                    profile.bid_end_date = form.cleaned_data['bid_end_date']
                    profile.save()

            return redirect('showroom:home_list')

    else:
        formset = profile_formset()

    return render(request, 'showroom/new_profile.html', {'formset': formset})

def search_profiles(request):

    query_name = request.GET.get('query')
    query_year = request.GET.get('year')
    query_engine = request.GET.get('engine')
    query_insured = request.GET.get('insured')

    filtered_profiles = Profile.objects.all()

    if query_name:
        filtered_profiles = filtered_profiles.filter(Q(name__icontains=query_name) | Q(variant__icontains=query_name))

    if query_year:
        filtered_profiles = filtered_profiles.filter(year=query_year)

    if query_engine:
        filtered_profiles = filtered_profiles.filter(engine=query_engine)

    if query_insured:
        filtered_profiles = filtered_profiles.filter(insured=query_insured)


    return render(request, 'showroom/search_results.html',
              {'filtered_profiles': filtered_profiles, 'query_name': query_name, 'query_year': query_year})    

def about_us_view(request):
    return render(request, 'showroom/Aboutus.html')

def Inventory_view(request):
    return render(request, 'showroom/Inventory.html')

showroom/templates/showroom/Carousel.html
<div style="flex: 1;">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <!-- First Membership Slide -->
                <div style="flex: 1; margin: 10px; border: 1px solid #ccc; border-radius: 10px; background-color: #F5FFFA; text-align: center;">
                    <img src="../media/Slide1.jpg" class="img-fluid" alt="Slide 1 Image">
                </div>
            </div>
            <div class="carousel-item">
                <!-- Second Membership Slide -->
                <div style="flex: 1; margin: 10px; border: 1px solid #ccc; border-radius: 10px; background-color: #F5FFFA; text-align: center;">
                    <img src="../media/Slide2.jpg" class="img-fluid" alt="Slide 2 Image">
                </div>
            </div>
            <div class="carousel-item">
                <!-- Third Membership Slide -->
                <div style="flex: 1; margin: 10px; border: 1px solid #ccc; border-radius: 10px; background-color: #F5FFFA; text-align: center;">
                    <img src="../media/Slide3.jpg" class="img-fluid" alt="Slide 3 Image">
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

showroom/templates/showroom/Inventory.html
{% extends 'showroom/base.html' %}
{% load static %}
{% block content %}
<h2 style="font-weight: bold; font-family: 'Arial', sans-serif; text-align: center;">Find Your Vehicle!</h2>
<div class="container" style="max-width: 600px; margin: 0 auto; border-radius: 30px; border: 2px solid #DCDCDC; background:#F5FFFA;">
    <h6 style="text-align: center; background-color: #FFD700; color: black; padding: 4px;border-radius: 30px;">Vehicle Finder</h6>
    <form method="GET" action="{% url 'showroom:search_profiles' %}">
        <div class="form-group">
            <label for="variantName">Make:</label>
            <input type="text" name="query" class="form-control" placeholder="Enter variant or name">
        </div>
        <div class="form-group">
            <label for="variantName">Model:</label>
            <input type="text" name="query" class="form-control" placeholder="Enter variant or name">
        </div>
        <div class="form-group">
            <label for="priceRange">Price Range:</label>
            <input type="range" name="price__range" class="form-control-range" min="2500000" max="10000000" step="10000"
                oninput="this.nextElementSibling.value = this.value" style="background-color: yellow;">
            <output>2,500,000</output>
            <output style="float: right;">10,000,000</output>
        </div>
        <div class="form-group">
            <label for="insured">Insurance status:</label>
            <select name="insured" class="form-control">
                <option value="">Select</option>
                <option value="yes">Insured</option>
                <option value="no">Not Insured</option>
            </select>
        </div>
        <div class="form-group">
            <label for="year">Year:</label>
            <input type="number" name="year" class="form-control" placeholder="Enter year">
        </div>
        <div class="form-group">
            <label for="mileageRange">Mileage Range (in KMs):</label>
            <input type="range" name="mileage__range" class="form-control-range" min="10000" max="100000" step="1000"
                oninput="this.nextElementSibling.value = this.value">
            <output>0</output>
            <output style="float: right;">100,000</output>
        </div>
        <div class="form-group">
            <label for="engineCapacity">Engine Capacity:</label>
            <input type="number" name="engine" class="form-control" placeholder="Enter engine capacity">
        </div>

        <div class="form-group text-center">
        <button type="submit" class="btn btn-warning rounded-lg">Find</button>
        </div>
    </form>
</div>
<br>

{% endblock %}

showroom/templates/showroom/base.html
{% load static %}
{% now 'Y-m-d H:i:s' as now %}
<!DOCTYPE html>
<html>
<head>
    <!-- Load Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
     <!-- Link your CSS file -->
    <title>AUTO LANKA | The No.1 Car Selling Platform</title>
</head>
<body>
    {% include 'showroom/search_bar.html' %}
    {% include 'showroom/header.html' %}


    <main role="main" class="container-fluid" style="background: linear-gradient(to left,#F5FFFA,#F0FFFF,#F5FFFA);">
        {% block content %}{% endblock %}
    </main>

    {% include 'showroom/Carousel.html' %}
    {% include 'showroom/membership.html' %}
    {% include 'showroom/footer.html' %}
    <!-- Load Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

showroom/templates/showroom/header.html
<nav class="navbar navbar-expand-lg navbar-dark" style="background: linear-gradient(to left,#4682B4, #000080, #191970, #000000);">
    <div class="container">
        <!-- Left-aligned items -->
        <nav class="navbar navbar-expand-lg navbar-light bg-transparent">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                MENU
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link btn  mr-2" href="{% url 'showroom:home_list' %}"
                           style="color: black; background-color: grey;"
                           onmouseover="this.style.color='grey'; this.style.backgroundColor='black';"
                           onmouseout="this.style.color='black'; this.style.backgroundColor='grey';">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn mr-2" href="{% url 'showroom:contact' %}"
                           style="color: black; background-color: grey;"
                           onmouseover="this.style.color='grey'; this.style.backgroundColor='black';"
                           onmouseout="this.style.color='black'; this.style.backgroundColor='grey';">Contact Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn  mr-2" href="{% url 'auction:profile_list' %}"
                           style="color: black; background-color: grey;"
                           onmouseover="this.style.color='grey'; this.style.backgroundColor='black';"
                           onmouseout="this.style.color='black'; this.style.backgroundColor='grey';">Bid on Profiles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn  mr-2" href="{% url 'showroom:Inventory' %}"
                           style="color: black; background-color: grey; border-width: 2px;"
                           onmouseover="this.style.color='grey'; this.style.backgroundColor='black';"
                           onmouseout="this.style.color='black'; this.style.backgroundColor='grey';">Inventory</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn  mr-2" href="{% url 'messaging:inbox' %}"
                           style="color: black; background-color: grey; border-width: 2px;"
                           onmouseover="this.style.color='grey'; this.style.backgroundColor='black';"
                           onmouseout="this.style.color='black'; this.style.backgroundColor='grey';">Messages</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn  mr-2" href="{% url 'showroom:Aboutus' %}"
                           style="color: black; background-color: grey; border-width: 2px;"
                           onmouseover="this.style.color='grey'; this.style.backgroundColor='black';"
                           onmouseout="this.style.color='black'; this.style.backgroundColor='grey';">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'showroom:new_profile' %}" type="button" class="btn btn-warning" style="padding: 9px 30px; font-size: 16px;">SELL YOUR VEHICLE</a>
                    </li>

                </ul>
            </div>
        </nav>

{% if user.is_authenticated %}
<div class="nav-item" style="position: relative; display: flex; align-items: center; margin-left: auto;"> <!-- Set margin-left to auto -->
    <div style="width: 40px; height: 40px; border-radius: 50%; background-color: white; color: #333; display: flex; justify-content: center; align-items: center; font-weight: bold; font-size: 18px;">
        {{ user.username|first|upper }}
        <div style="width: 12px; height: 12px; background-color: green; border-radius: 50%; margin-left: 5px;"></div>
    </div>
    <div style="margin-left: 10px; margin-top: 10px;"> <!-- Increased margin-top to move the text further down -->
        <p style="color: white; font-weight: bold;">Hi, {{ user.username }}</p>
    </div>
</div>
{% endif %}

    </div>
</nav>

showroom/templates/showroom/home_list.html
{% extends 'showroom/base.html' %}
{% block content %}
<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center">
        <form method="GET" action="" class="d-flex">
            <select name="sort" id="sort" class="mr-2 form-control" style="border-radius: 10px;">
                <option value="">Select an option</option>
                <option value="name">Brand</option>
                <option value="variant">Model</option>
                <option value="year">Year</option>
            </select>
            <button type="submit" class="btn btn-warning" style="border-radius: 10px;">Sort</button>
        </form>

<div class="row justify-content-end" style="margin-right: 4px;">
    <ul class="pagination">
        {% if profiles.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" style="color: black;">&laquo; First</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ profiles.previous_page_number }}" style="color: black;">Previous</a>
        </li>
        {% endif %}

        <li class="page-item disabled">
            <span class="page-link">
                Page {{ profiles.number }} of {{ profiles.paginator.num_pages }}
            </span>
        </li>

        {% if profiles.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ profiles.next_page_number }}" style="color: black;">Next</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ profiles.paginator.num_pages }}" style="color: black;">Last &raquo;</a>
        </li>
        {% endif %}
    </ul>
</div>

    </div>
</div>
<br>
<div class="container">
    <div class="row">
        {% for profile in profiles %}
        <div class="col-md-4">
            <div class="card shadow mb-4" style="border-radius: 30px;">
                <img class="card-img-top" src="{{ profile.pic.url }}" alt="Profile picture" style="height: 200px; object-fit: cover;">
                    <div class="card-body text-center">
                        <h5 class="card-title text-uppercase font-weight-bold">{{ profile.year }} {{ profile.name }}</h5>
                        <span class="d-block" style="color: #00008B; font-weight: bold;">Model: {{ profile.variant }}</span>
                        <span class="d-block" style="color: green; font-weight: bold;">Current Bid: LKR {{ profile.price }}</span>
                        <a href="{% url 'showroom:profiles' profile.id %}" class="btn btn-warning mt-3">View Profile</a>
                        {% with formatted_bid_end_date=profile.bid_end_date|date:'Y-m-d H:i:s' %}
                        {% if formatted_bid_end_date > now %}
                            <a href="{% url 'auction:place_bid' profile.id %}" class="btn btn-success">Place Bid</a>
                        {% else %}
                            <p>Bidding Closed</p>
                        {% endif %}
                        {% endwith %}
                    </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<!-- Pagination Controls -->
<div class="row justify-content-center">
    <ul class="pagination">
        {% if profiles.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" style="color: black;">&laquo; First</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ profiles.previous_page_number }}" style="color: black;">Previous</a>
        </li>
        {% endif %}

        <li class="page-item disabled">
            <span class="page-link">
                Page {{ profiles.number }} of {{ profiles.paginator.num_pages }}
            </span>
        </li>

        {% if profiles.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ profiles.next_page_number }}" style="color: black;">Next</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ profiles.paginator.num_pages }}" style="color: black;">Last &raquo;</a>
        </li>
        {% endif %}
    </ul>
</div>

{% endblock %}

showroom/templates/showroom/membership.html
<div style="display: flex; background-color: #000000; padding: 20px;">
          <hr style="border: 1px solid rgba(0, 0, 0, 0.5); margin-top: 20px;">

    <div style="flex: 1; padding-right: 20px; ">
        <h1 style="color: #DAA520; text-align: center; margin-top: 20px; font-weight: bold; font-family: 'Arial', sans-serif;">MEMBERSHIP OPTIONS</h1>
        <p style="text-align: center; color: #F0F8FF; margin: 0 20px; font-family: 'Arial', sans-serif; font-size: 18px; font-weight: bold; text-align: justify;">
        Enroll in our car membership program to access a spectrum of privileges, encompassing discounted services, expedited priority bookings, and bespoke, limited-time offers meticulously crafted to elevate and redefine your experience.
        </p>
        <br>


        <div style="display: flex; justify-content: center; font-family: Arial, sans-serif;">
              <ul style="list-style: none; padding: 0; display: flex;">
                <li style="color: #F0F8FF; display: flex; align-items: center; margin-right: 20px;">
                  <span style="color: #DAA520; margin-right: 5px;">✔</span> ANNUAL PAYMENT
                </li>
                <li style="color: #F0F8FF; display: flex; align-items: center; margin-right: 20px;">
                  <span style="color: #DAA520; margin-right: 5px;">✔</span> REFUND AVAILABLE
                </li>
                <li style="color: #F0F8FF; display: flex; align-items: center;">
                  <span style="color: #DAA520; margin-right: 5px;">✔</span> INFINITY ACCESS
                </li>
              </ul>
        </div>
        <div style="text-align: center; margin-top: 0.125px;">
        <a href="{% url 'account:register' %}" class="btn btn-outline-dark" style="background-color: #DAA520; color: black; padding: 10px 20px; text-decoration: none;">BECOME A MEMBER</a>
        </div>
    </div>

  <!-- Membership Slideshow -->
<div style="flex: 1;">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <!-- First Membership Slide -->
                <div style="flex: 1; margin: 10px; border: 1px solid #ccc; padding: 20px; border-radius: 10px; background-color: #F5FFFA;">
                    <h2 style="margin-top: 0; text-align: center; font-family: Arial, sans-serif; font-weight: bold; color: #00008B;">Essential Seller</h2>
                    <p style="text-align: center;">Our Starter Package, the Essential Seller tier, empowers newcomers with essential tools. Create 5 detailed listings, connect with buyers, and access basic analytics for performance insights. Perfect for those starting their car-selling journey, offering a straightforward approach to online sales.</p>
                    <strong style="display: block; text-align: center; color: green;">Starting from LKR 5,000</strong>
                </div>
            </div>
            <div class="carousel-item">
                <!-- Second Membership Slide -->
                <div style="flex: 1; margin: 10px; border: 1px solid #ccc; padding: 20px; border-radius: 10px; background-color: #F5FFFA;">
                    <h2 style="margin-top: 0; text-align: center; font-family: Arial, sans-serif; font-weight: bold; color: #00008B;">Premium Seller</h2>
                    <p style="text-align: center;">The Premium Seller tier, our Advanced Package, elevates visibility and sales potential. Gain priority placement, unlimited listings, and detailed analytics for effective selling strategies. Utilize promotional tools and dedicated support for optimized selling, perfect for sellers seeking increased exposure and advanced insights.</p>
                    <strong style="display: block; text-align: center; color: green;">Starting from LKR 10,000</strong>
                </div>
            </div>
            <div class="carousel-item">
                <!-- Third Membership Slide -->
                <div style="flex: 1; margin: 10px; border: 1px solid #ccc; padding: 20px; border-radius: 10px; background-color: #F5FFFA;">
                    <h2 style="margin-top: 0; text-align: center; font-family: Arial, sans-serif; font-weight: bold; color: #00008B;">Elite Seller</h2>
                    <p style="text-align: center;">Our Professional Package, the Elite Seller tier, caters to high-volume sellers and dealerships. Enjoy VIP placement, dedicated account management, specialized promotions, advanced security, and exclusive discounts. Tailored for top-tier sellers aiming for maximum exposure, security, and market dominance.</p>
                    <strong style="display: block; text-align: center; color: green;">Starting from LKR 50,000</strong>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
         <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

</div>

showroom/templates/showroom/search_bar.html
<div class="navbar navbar-expand-lg navbar-dark" style="background: linear-gradient(to left,#4682B4, #000080, #191970, #000000);">
<div class="row">
    <form method="GET" action="{% url 'showroom:search_profiles' %}" class="d-flex align-items-start w-100 ml-3">
        <input type="text" name="query" placeholder="Search vehicle..." class="form-control border-0 rounded-lg mr-3" style="width: 50%;">
        <input type="number" name="year" placeholder="Filter by year" class="form-control border-0 rounded-lg mr-3" style="width: 30%;">
        <button type="submit" class="btn btn-warning rounded-lg">Search</button>
    </form>
</div>

    <a class="navbar-brand mx-auto" href="#">
    <img src="https://i.imgur.com/0EiboL1.png" alt="Auto Lanka Logo" height="40" width="auto">
    <span class="text-light" style="font-weight: bold; letter-spacing: 2px; font-size: 24px;">AUTO </span>
        <span class="text" style="font-weight: bold; letter-spacing: 2px; font-size: 24px; color: #DAA520;">LANKA</span>

    </a>
    <nav class="navbar navbar-expand-lg navbar-light bg-transparent">
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
        <li class="nav-item d-none d-lg-block">
            <a class="nav-link btn btn-warning mr-2 text-dark" href="{% url 'account:logout' %}" style="border-width: 2px;">Logout</a>
        </li>
            {% else %}
        <li class="nav-item d-none d-lg-block">
            <a class="nav-link btn btn-warning mr-2 text-dark" href="{% url 'account:login' %}" style="border-width: 2px;">Login</a>
        </li>
            {% endif %}
        <li class="nav-item d-none d-lg-block">
            <a class="nav-link btn btn-dark text-white" href="{% url 'account:register' %}" style="border-width: 2px;">SignUp</a>
        </li>
    </ul>
</div>

    </nav>
</div>

showroom/templates/showroom/search_results.html
{% extends 'showroom/base.html' %}
{% load static %}
{% block content %}

{% if filtered_profiles %}
    <h2>Search Results for "{{ query_name }} {{ query_year }}"</h2>
<div class="container">
    <div class="row">
        {% for profile in filtered_profiles %}
        <div class="col-md-4">
            <div class="card shadow mb-4" style="border-radius: 30px;">
                <img class="card-img-top" src="{{ profile.pic.url }}" alt="Profile picture" style="height: 200px; object-fit: cover;">
                    <div class="card-body text-center">
                        <h5 class="card-title text-uppercase font-weight-bold">{{ profile.year }} {{ profile.name }}</h5>
                        <span class="d-block" style="color: #00008B; font-weight: bold;">Model: {{ profile.variant }}</span>
                        <span class="d-block" style="color: green; font-weight: bold;">Current Bid: LKR {{ profile.price }}</span>
                        <a href="{% url 'showroom:profiles' profile.id %}" class="btn btn-warning mt-3">View Profile</a>
                    </div>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
    <h3>OOPS! No profiles found. Please try again.</h3>
{% endif %}

{% endblock %}